### PR TITLE
V2.0

### PR DESCRIPTION
**Pull request by NotKaskus**

### CODE REVIEW

**Comment by NotKaskus** [comment]
some image endpoint is broken, also broke = returning blank white page
https://github.com/BearTS/tamako-microservices/pull/3/commits/2d25d9e8352326313b0aabf61017bffba5d689eb#diff-859914a8700bc0fbbd8a5511d948446c97789085a2e11b891a5733850d660ba7

**Comment by NotKaskus** [comment]
ill try to fix them after i complete edit-meme

**Comment by BearTS** [comment]
@NotKaskus Ready to merge?

**Comment by NotKaskus** [comment]
yup

**Comment by BearTS** [comment]
Aye! I will review the changes and merge

**Review by BearTS — APPROVED** [review]
LGTM

**Pull request merged**
